name: Frama-C Verification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Install system dependencies for Frama-C
      - name: Install Required System Dependencies
        run: |
          sudo apt update
          sudo apt install -y opam ocaml ocaml-base ocaml-native-compilers
          sudo apt install -y graphviz libcairo2-dev libgtk-3-dev libgtksourceview-3.0-dev

      # Initialize OPAM
      - name: Initialize OPAM
        run: |
          opam init --disable-sandboxing --yes
          eval $(opam env)
          echo "eval $(opam env)" >> $GITHUB_ENV

      # Install Frama-C
      - name: Install Frama-C via OPAM
        run: |
          source $GITHUB_ENV
          opam install -y frama-c

      # Run Frama-C verification on all C files
      - name: Verify with Frama-C
        run: |
          source $GITHUB_ENV
          for file in *.c; do
            echo "Verifying $file..."
            frama-c -wp -wp-rte "$file" || exit 1
          done
