name: Frama-C Verification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Install Frama-C and dependencies
      - name: Install Frama-C
        run: |
          sudo apt update
          sudo apt install -y frama-c frama-c-base

      # Run Frama-C verification on all C files
      - name: Verify with Frama-C
        run: |
          for file in *.c; do
            echo "Verifying $file"
            frama-c -wp -wp-rte "$file" || exit 1
          done
