name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y opam
          opam init --disable-sandboxing --yes
          eval $(opam env)
          opam update --yes
          opam upgrade --yes

      - name: Build and Test
        run: |
          opam switch create 4.08.1_fc22 ocaml-base-compiler.4.08.1 --yes
          eval $(opam env)
          opam install depext --yes
          opam depext frama-c.22.0 --yes
          opam install alt-ergo.2.3.0 why3.1.3.3 frama-c.22.0 frama-c-metacsl.0.1 --yes
          why3 config --detect
