name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-frama-c .

      - name: Run WP proofs
        run: |
          # For each .c file, run frama-c -wp
          docker run --rm my-frama-c frama-c -wp maxint.c
          docker run --rm my-frama-c frama-c -wp maxint3.c
          docker run --rm my-frama-c frama-c -wp loops.c
          docker run --rm my-frama-c frama-c -wp abs.c
          docker run --rm my-frama-c frama-c -wp sum.c
          docker run --rm my-frama-c frama-c -wp foo.c
          docker run --rm my-frama-c frama-c -wp getIndexMin.c
          docker run --rm my-frama-c frama-c -wp allZeros.c
          docker run --rm my-frama-c frama-c -wp equal.c
          docker run --rm my-frama-c frama-c -wp fill.c
          docker run --rm my-frama-c frama-c -wp fact.c
